/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sagar
 */
//import the package
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
         super("LoginForm");
        initComponents();
        label_star1.setVisible(false);
        label_star2.setVisible(false);
        this.setLocationRelativeTo(null);
        setResizable(false);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        showPass = new javax.swing.JCheckBox();
        label_star1 = new javax.swing.JLabel();
        label_star2 = new javax.swing.JLabel();
        registerNewUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(214748364, 2147483647));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        password.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, -1));

        login.setBackground(new java.awt.Color(0, 153, 102));
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 74, 33));

        cancel.setBackground(new java.awt.Color(255, 51, 51));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 33));

        showPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        showPass.setForeground(new java.awt.Color(102, 153, 255));
        showPass.setText("Show Pass");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel1.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));

        label_star1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_star1.setForeground(new java.awt.Color(255, 0, 0));
        label_star1.setText("*");
        jPanel1.add(label_star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 15, -1));

        label_star2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_star2.setForeground(new java.awt.Color(255, 0, 0));
        label_star2.setText("*");
        jPanel1.add(label_star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        registerNewUser.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        registerNewUser.setForeground(new java.awt.Color(255, 255, 255));
        registerNewUser.setText("Don't have a username? Create a new User.");
        registerNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerNewUserMouseClicked(evt);
            }
        });
        jPanel1.add(registerNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UserName:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginn.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 430, 370));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerNewUserMouseClicked
        RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        //pack() method sizes the frame so that its all contents  are at or above their preferred sizes
        rgf.pack();
        //setLocationRelativeTo(null) sets the frame appear on the center of the screen.
        rgf.setLocationRelativeTo(null);
        //Makes the register form only gets closed on clicking the cancel icon.
        //Program donot get stopped.
        rgf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_registerNewUserMouseClicked

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        if (showPass.isSelected()) {
            // Setting a value of 0 indicates that we  wish to see the text as it is typed.
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        //the below method exits current program by terminating the java virtual machine.
        //it generally represents the succesful termination of the current program.
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:

        label_star1.setVisible(false);
        label_star2.setVisible(false);
        if (username.getText().equals("")) {
            label_star1.setVisible(true);
        }

        if (String.valueOf(password.getPassword()).equals("")) {
            label_star2.setVisible(true);
        }  else {
            try {
                //instantiating the Connection object by calling getConnection method.
                Connection con = MyConnection.getConnection();
                //Creating the statement.
                PreparedStatement pst = con.prepareStatement("SELECT * FROM user WHERE username= ? AND password= ?");
                pst.setString(1, username.getText());
                pst.setString(2, String.valueOf(password.getPassword()));
                //Executing the query and keeping the table like structure in the ResultSet object.
                //If we only want to fetch the table's datas then we use the executeQuery method.
                //But here if we had to insert,update or remove the datas of the table we use executeUpdate msethod.
                ResultSet rs = pst.executeQuery();

                //Here rs.next() it does the 2 things,1st it shifts the pointer to the next line and second it checks
                // whether it has the datas or not if yes it enters inside  the loop,if no it escapes away from the loop.
                if (rs.next()) {
                    // Splash1 ss=new Splash1();
                    MainForm mf = new MainForm();
                    mf.setVisible(true);
                    mf.pack();
                    //Make the MainForm frame display in the center of  the screen.
                    mf.setLocationRelativeTo(null);
                    //mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    MainForm.welcome.setText("Welcome " + username.getText()+"          |          |" );
                    //Calling the countData function to display the total number of accessories.
                    MainForm.totalAccesories.setText("Total Accessories : " + Integer.toString(MyFunction.countData("accessory")));
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, " Incorrect UserName or Password", "Login Failed", 2);
                }

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

    }//GEN-LAST:event_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
                 

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_star1;
    private javax.swing.JLabel label_star2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerNewUser;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
